general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock
}

# Turn screen off 30 seconds after lock
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on eDP-1 ; hyprctl dispatch dpms on HDMI-A-1
}

# Suspend after 30 minutes idle (only if no active SSH or samba)
listener {
    timeout = 1800
    on-timeout = bash -c "if ! ss -tnp | grep -qE 'sshd|smbd'; then systemctl suspend; fi"
}
